//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormGTI.UserWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWcf", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Classe")]
    [System.SerializableAttribute()]
    public partial class UserWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfCnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormGTI.UserWCF.Mensagem StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CpfCnpj {
            get {
                return this.CpfCnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfCnpjField, value) != true)) {
                    this.CpfCnpjField = value;
                    this.RaisePropertyChanged("CpfCnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateAt {
            get {
                return this.CreateAtField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateAtField, value) != true)) {
                    this.CreateAtField = value;
                    this.RaisePropertyChanged("CreateAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormGTI.UserWCF.Mensagem Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateAt {
            get {
                return this.UpdateAtField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateAtField, value) != true)) {
                    this.UpdateAtField = value;
                    this.RaisePropertyChanged("UpdateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensagem", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Classe")]
    [System.SerializableAttribute()]
    public partial class Mensagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoreInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoreInformation {
            get {
                return this.MoreInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreInformationField, value) != true)) {
                    this.MoreInformationField = value;
                    this.RaisePropertyChanged("MoreInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWCF.IUserWcfService")]
    public interface IUserWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetAllUsers", ReplyAction="http://tempuri.org/IUserWcfService/GetAllUsersResponse")]
        WebFormGTI.UserWCF.UserWcf[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetAllUsers", ReplyAction="http://tempuri.org/IUserWcfService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetUserById", ReplyAction="http://tempuri.org/IUserWcfService/GetUserByIdResponse")]
        WebFormGTI.UserWCF.UserWcf GetUserById(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetUserById", ReplyAction="http://tempuri.org/IUserWcfService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf> GetUserByIdAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/AddUser", ReplyAction="http://tempuri.org/IUserWcfService/AddUserResponse")]
        void AddUser(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/AddUser", ReplyAction="http://tempuri.org/IUserWcfService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/UpdateUser", ReplyAction="http://tempuri.org/IUserWcfService/UpdateUserResponse")]
        void UpdateUser(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/UpdateUser", ReplyAction="http://tempuri.org/IUserWcfService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/DeleteUser", ReplyAction="http://tempuri.org/IUserWcfService/DeleteUserResponse")]
        void DeleteUser(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/DeleteUser", ReplyAction="http://tempuri.org/IUserWcfService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserWcfServiceChannel : WebFormGTI.UserWCF.IUserWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWcfServiceClient : System.ServiceModel.ClientBase<WebFormGTI.UserWCF.IUserWcfService>, WebFormGTI.UserWCF.IUserWcfService {
        
        public UserWcfServiceClient() {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebFormGTI.UserWCF.UserWcf[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WebFormGTI.UserWCF.UserWcf GetUserById(int productId) {
            return base.Channel.GetUserById(productId);
        }
        
        public System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf> GetUserByIdAsync(int productId) {
            return base.Channel.GetUserByIdAsync(productId);
        }
        
        public void AddUser(WebFormGTI.UserWCF.UserWcf product) {
            base.Channel.AddUser(product);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(WebFormGTI.UserWCF.UserWcf product) {
            return base.Channel.AddUserAsync(product);
        }
        
        public void UpdateUser(WebFormGTI.UserWCF.UserWcf product) {
            base.Channel.UpdateUser(product);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(WebFormGTI.UserWCF.UserWcf product) {
            return base.Channel.UpdateUserAsync(product);
        }
        
        public void DeleteUser(int productId) {
            base.Channel.DeleteUser(productId);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int productId) {
            return base.Channel.DeleteUserAsync(productId);
        }
    }
}
