//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormGTI.UserWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWcf", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Classe")]
    [System.SerializableAttribute()]
    public partial class UserWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_ExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormGTI.UserWCF.Endereco Endereco_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estado_CivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Orgao_ExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_Expedicao {
            get {
                return this.Data_ExpedicaoField;
            }
            set {
                if ((this.Data_ExpedicaoField.Equals(value) != true)) {
                    this.Data_ExpedicaoField = value;
                    this.RaisePropertyChanged("Data_Expedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormGTI.UserWCF.Endereco Endereco_Cliente {
            get {
                return this.Endereco_ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Endereco_ClienteField, value) != true)) {
                    this.Endereco_ClienteField = value;
                    this.RaisePropertyChanged("Endereco_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado_Civil {
            get {
                return this.Estado_CivilField;
            }
            set {
                if ((object.ReferenceEquals(this.Estado_CivilField, value) != true)) {
                    this.Estado_CivilField = value;
                    this.RaisePropertyChanged("Estado_Civil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orgao_Expedicao {
            get {
                return this.Orgao_ExpedicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Orgao_ExpedicaoField, value) != true)) {
                    this.Orgao_ExpedicaoField = value;
                    this.RaisePropertyChanged("Orgao_Expedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Classe")]
    [System.SerializableAttribute()]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Cliente {
            get {
                return this.Id_ClienteField;
            }
            set {
                if ((this.Id_ClienteField.Equals(value) != true)) {
                    this.Id_ClienteField = value;
                    this.RaisePropertyChanged("Id_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWCF.IUserWcfService")]
    public interface IUserWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetAllUsers", ReplyAction="http://tempuri.org/IUserWcfService/GetAllUsersResponse")]
        WebFormGTI.UserWCF.UserWcf[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetAllUsers", ReplyAction="http://tempuri.org/IUserWcfService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetUserById", ReplyAction="http://tempuri.org/IUserWcfService/GetUserByIdResponse")]
        WebFormGTI.UserWCF.UserWcf GetUserById(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/GetUserById", ReplyAction="http://tempuri.org/IUserWcfService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf> GetUserByIdAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/AddUser", ReplyAction="http://tempuri.org/IUserWcfService/AddUserResponse")]
        void AddUser(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/AddUser", ReplyAction="http://tempuri.org/IUserWcfService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/UpdateUser", ReplyAction="http://tempuri.org/IUserWcfService/UpdateUserResponse")]
        void UpdateUser(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/UpdateUser", ReplyAction="http://tempuri.org/IUserWcfService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(WebFormGTI.UserWCF.UserWcf product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/DeleteUser", ReplyAction="http://tempuri.org/IUserWcfService/DeleteUserResponse")]
        void DeleteUser(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserWcfService/DeleteUser", ReplyAction="http://tempuri.org/IUserWcfService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserWcfServiceChannel : WebFormGTI.UserWCF.IUserWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWcfServiceClient : System.ServiceModel.ClientBase<WebFormGTI.UserWCF.IUserWcfService>, WebFormGTI.UserWCF.IUserWcfService {
        
        public UserWcfServiceClient() {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebFormGTI.UserWCF.UserWcf[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WebFormGTI.UserWCF.UserWcf GetUserById(int productId) {
            return base.Channel.GetUserById(productId);
        }
        
        public System.Threading.Tasks.Task<WebFormGTI.UserWCF.UserWcf> GetUserByIdAsync(int productId) {
            return base.Channel.GetUserByIdAsync(productId);
        }
        
        public void AddUser(WebFormGTI.UserWCF.UserWcf product) {
            base.Channel.AddUser(product);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(WebFormGTI.UserWCF.UserWcf product) {
            return base.Channel.AddUserAsync(product);
        }
        
        public void UpdateUser(WebFormGTI.UserWCF.UserWcf product) {
            base.Channel.UpdateUser(product);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(WebFormGTI.UserWCF.UserWcf product) {
            return base.Channel.UpdateUserAsync(product);
        }
        
        public void DeleteUser(int productId) {
            base.Channel.DeleteUser(productId);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int productId) {
            return base.Channel.DeleteUserAsync(productId);
        }
    }
}
